import axios from 'axios';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { AISuggestion, AnalysisResult, GrammarIssue, ToneAnalysis } from '../types';
import { checkGrammar, computeGrammarScore } from './grammarCheck';

// ─── Cost-control constants ────────────────────────────────────────────────────
// Gemini Flash input window is large, but we cap ← keeps latency + cost low
const MAX_GEMINI_CHARS   = 4_000;   // ~1 000 tokens; enough for dense analysis
const MAX_GRAMMAR_CHARS  = 10_000;  // LanguageTool handles bigger chunks cheaply
const MIN_ANALYSIS_CHARS = 50;      // reject nonsense / empty pings

// ─── Gemini client (lazy init) ────────────────────────────────────────────────

let _gemini: GoogleGenerativeAI | null = null;

function getGemini(): GoogleGenerativeAI {
  if (!_gemini) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY is not configured');
    _gemini = new GoogleGenerativeAI(apiKey);
  }
  return _gemini;
}

// ─── AI Content Analysis (Gemini) ───────────────────────────────────────────

async function analyseAIContent(text: string): Promise<{
  score: number | null;
  reasoning: string;
  humanizationTips: string[];
}> {
  const sample = text.slice(0, MAX_GEMINI_CHARS);

  const model = getGemini().getGenerativeModel({
    model: 'gemini-2.5-flash',
    generationConfig: { responseMimeType: 'application/json', temperature: 0.1 },
  });

  const prompt = `You are a forensic AI-text detection expert with deep knowledge of NLP, stylometry, and human writing patterns.

Thoroughly analyse the following text and determine whether it was written by a human or generated by an AI language model.

Detection criteria to evaluate:
1. Sentence uniformity — AI text has consistent lengths and rhythms
2. Hedge phrases — "It is important to note", "In conclusion", "It is worth mentioning"
3. Vocabulary — AI avoids rare/colloquial words, overuses formal synonyms
4. Specificity — Human writing has concrete details, personal anecdotes; AI generalises
5. Transitions — AI overuses "Furthermore", "Moreover", "Additionally"
6. Emotion & personality — Human writing has voice, quirks, imperfections
7. Factual precision — AI gives vague statistics or overly generic examples

Then provide SPECIFIC, ACTIONABLE tips to make AI-generated content sound more human.

Return ONLY valid JSON (no markdown):
{
  "aiLikelihoodScore": <integer 0-100, where 100 = definitely AI>,
  "reasoning": "<2-3 sentences citing specific evidence from the text>",
  "humanizationTips": [
    "<Specific tip 1 — e.g. Replace the opener 'It is important to note' with a direct statement>",
    "<Specific tip 2>",
    "<Specific tip 3>",
    "<Specific tip 4>",
    "<Specific tip 5>"
  ]
}

Text:
"""
${sample}
"""`;

  try {
    const result = await model.generateContent(prompt);
    const raw = result.response.text().trim()
      .replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
    const parsed = JSON.parse(raw) as {
      aiLikelihoodScore?: number;
      reasoning?: string;
      humanizationTips?: string[];
    };
    return {
      score: Math.min(100, Math.max(0, parsed.aiLikelihoodScore ?? 0)),
      reasoning: parsed.reasoning ?? '',
      humanizationTips: (parsed.humanizationTips ?? []).slice(0, 7),
    };
  } catch (err) {
    console.error('AI content analysis failed:', err);
    return { score: null, reasoning: '', humanizationTips: [] };
  }
}

// ─── Style Suggestions ────────────────────────────────────────────────────────

async function generateSuggestions(text: string): Promise<AISuggestion[]> {
  const sample = text.slice(0, MAX_GEMINI_CHARS);

  const model = getGemini().getGenerativeModel({
    model: 'gemini-2.5-flash',
    generationConfig: {
      responseMimeType: 'application/json',
      temperature: 0.4,
    },
  });

  const prompt = `You are a professional editor, writing coach, and communication expert.

Review the following text thoroughly and provide up to 8 actionable improvement tips.
For each tip, identify a SPECIFIC passage from the text and explain exactly how to improve it.

Tip types to consider:
- "rewrite": Restructure a sentence or paragraph for better flow
- "simplify": Replace complex or jargon-heavy phrases with clearer language
- "expand": Add missing detail, evidence, or explanation
- "tone": Adjust formality, voice, or emotional register
- "clarity": Fix ambiguous pronouns, unclear antecedents, confusing structure
- "vocabulary": Replace weak, vague, or repetitive word choices
- "structure": Improve paragraph organisation, transitions, or logical flow
- "concise": Remove filler words, redundancy, or unnecessary repetition

Return ONLY a valid JSON array (no markdown, no extra text):
[
  {
    "type": "rewrite|simplify|expand|tone|clarity|vocabulary|structure|concise",
    "original": "<exact excerpt from text, max 150 chars>",
    "suggested": "<improved version with specific change>",
    "reason": "<concise explanation of why this improves the writing>"
  }
]

Text:
"""
${sample}
"""`;

  try {
    const result = await model.generateContent(prompt);
    const raw = result.response.text().trim()
      .replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');

    const parsed = JSON.parse(raw) as AISuggestion[] | { suggestions?: AISuggestion[] };
    const suggestions = Array.isArray(parsed) ? parsed : (parsed.suggestions ?? []);
    return suggestions.slice(0, 8);
  } catch (err) {
    console.error('Suggestion generation failed:', err);
    return [];
  }
}

// ─── Syllable estimator ───────────────────────────────────────────────────────

function estimateSyllables(word: string): number {
  word = word.toLowerCase().replace(/[^a-z]/g, '');
  if (word.length <= 3) return 1;
  const vowels = word.match(/[aeiouy]+/g);
  return vowels ? vowels.length : 1;
}

function fleschGrade(score: number): string {
  if (score >= 90) return 'Very Easy (5th grade)';
  if (score >= 80) return 'Easy (6th grade)';
  if (score >= 70) return 'Fairly Easy (7th grade)';
  if (score >= 60) return 'Standard (8th-9th grade)';
  if (score >= 50) return 'Fairly Difficult (10th-12th grade)';
  if (score >= 30) return 'Difficult (College)';
  return 'Very Confusing (Professional)';
}

// ─── Readability (local Flesch + optional TextGears) ─────────────────────────

async function computeReadabilityScore(text: string): Promise<{
  score: number;
  wordCount: number;
  sentenceCount: number;
  readingTimeMinutes: number;
  fleschGradeLevel: string;
  avgSentenceLength: number;
}> {
  const words = text.trim().split(/\s+/).filter(Boolean);
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const wordCount = words.length;
  const sentenceCount = Math.max(sentences.length, 1);
  const avgSentenceLength = wordCount / sentenceCount;
  const readingTimeMinutes = wordCount / 238;

  const avgSyllables =
    words.reduce((sum, w) => sum + estimateSyllables(w), 0) / Math.max(wordCount, 1);
  let localScore = Math.round(206.835 - 1.015 * avgSentenceLength - 84.6 * avgSyllables);
  localScore = Math.min(100, Math.max(0, localScore));

  // Try TextGears for enhanced readability (optional)
  // Response shape: { status, response: { stats: { fleschKincaid: { readingEase, grade, interpretation }, gunningFog, emotion: { positive, negative }, counters: { words, sentences } } } }
  const tgKey = process.env.TEXTGEARS_API_KEY;
  let finalScore = localScore;
  let finalGrade = fleschGrade(localScore);

  if (tgKey && wordCount >= 30) {
    try {
      interface TGStats {
        fleschKincaid?: { readingEase?: number; grade?: string; interpretation?: string };
        gunningFog?: number;
        colemanLiau?: number;
        emotion?: { positive?: number; negative?: number };
        counters?: { words?: number; sentences?: number };
      }
      type TGResponse = { status?: boolean; response?: { stats?: TGStats } };

      const res = await axios.get<TGResponse>(
        'https://api.textgears.com/readability',
        {
          params: { key: tgKey, text: text.slice(0, MAX_GEMINI_CHARS), language: 'en-US' },
          timeout: 10_000,
        }
      );

      if (res.data?.status !== false) {
        const stats = res.data?.response?.stats;
        const fk = stats?.fleschKincaid;

        if (typeof fk?.readingEase === 'number') {
          finalScore = Math.min(100, Math.max(0, Math.round(fk.readingEase)));
        }
        // Use the API's own grade label if available, otherwise fall back to local mapping
        if (fk?.grade) {
          finalGrade = fk.interpretation
            ? `${fk.grade} — ${fk.interpretation}`
            : fk.grade;
        } else {
          finalGrade = fleschGrade(finalScore);
        }
      }
    } catch (e) {
      console.warn('TextGears readability fallback to local:', (e as Error).message);
    }
  }

  return { score: finalScore, wordCount, sentenceCount, readingTimeMinutes, fleschGradeLevel: finalGrade, avgSentenceLength };
}

// ─── Tone Analysis (Gemini) ──────────────────────────────────────────────────
// Twinword will be plugged in later; Gemini handles tone for now.

async function computeToneAnalysis(text: string): Promise<ToneAnalysis> {
  const sample = text.slice(0, MAX_GEMINI_CHARS);

  // Twinword hook — will be activated once RAPIDAPI_KEY is provided
  const rapidKey = process.env.RAPIDAPI_KEY;
  if (rapidKey) {
    try {
      type TwinResponse = { result?: string; confidence?: number; emotions?: Record<string, number> };
      const res = await axios.post<TwinResponse>(
        'https://twinword-sentiment-analysis.p.rapidapi.com/analyze/',
        new URLSearchParams({ text: sample }),
        {
          headers: {
            'content-type': 'application/x-www-form-urlencoded',
            'X-RapidAPI-Key': rapidKey,
            'X-RapidAPI-Host': 'twinword-sentiment-analysis.p.rapidapi.com',
          },
          timeout: 8_000,
        }
      );
      const d = res.data;
      if (d?.result) {
        const dominant = d.result.toLowerCase();
        const confidence = typeof d.confidence === 'number' ? d.confidence : 0.7;
        const scores: Record<string, number> = d.emotions
          ? Object.fromEntries(Object.entries(d.emotions).map(([k, v]) => [k, Math.min(1, Math.max(0, v))]))
          : { [dominant]: confidence };
        return { dominant, confidence, scores, description: `Text has a ${dominant} tone with ${Math.round(confidence * 100)}% confidence.` };
      }
    } catch (e) {
      console.warn('Twinword unavailable, using Gemini for tone:', (e as Error).message);
    }
  }

  // Gemini tone analysis
  const model = getGemini().getGenerativeModel({
    model: 'gemini-2.5-flash',
    generationConfig: { responseMimeType: 'application/json', temperature: 0.2 },
  });

  const prompt = `You are an expert linguist specialising in stylometric analysis and tone detection.

Analyse the writing tone of the following text across these six dimensions:
- formal: Academic, professional, structured language
- conversational: Friendly, casual, approachable
- persuasive: Opinionated, argumentative, convincing
- technical: Domain-specific, precise, jargon-heavy
- narrative: Storytelling, descriptive, experiential
- instructional: Step-by-step, directive, how-to

Return ONLY valid JSON (no markdown):
{
  "dominant": "<single most prominent tone from the 6 above>",
  "confidence": <float 0.0-1.0>,
  "scores": {
    "formal": <float 0.0-1.0>,
    "conversational": <float 0.0-1.0>,
    "persuasive": <float 0.0-1.0>,
    "technical": <float 0.0-1.0>,
    "narrative": <float 0.0-1.0>,
    "instructional": <float 0.0-1.0>
  },
  "description": "<1-2 sentence description of the text's tone and writing style>"
}

Text:
"""
${sample}
"""`;

  try {
    const result = await model.generateContent(prompt);
    const raw = result.response.text().trim()
      .replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
    const parsed = JSON.parse(raw) as ToneAnalysis;
    if (!parsed?.dominant) throw new Error('Invalid tone response');
    return {
      dominant: parsed.dominant,
      confidence: Math.min(1, Math.max(0, parsed.confidence ?? 0.5)),
      scores: parsed.scores ?? {},
      description: parsed.description,
    };
  } catch (err) {
    console.error('Gemini tone analysis failed:', err);
    return { dominant: 'neutral', confidence: 0.5, scores: { neutral: 0.5 }, description: 'Tone analysis unavailable.' };
  }
}

// ─── Plagiarism Placeholder ───────────────────────────────────────────────────

function computePlagiarismScore(): number {
  return 0;
}

// ─── Main Analysis Function ───────────────────────────────────────────────────

export async function analyseDocument(text: string): Promise<AnalysisResult> {
  if (!text || text.trim().length < MIN_ANALYSIS_CHARS) {
    throw new Error(`Text is too short to analyse (minimum ${MIN_ANALYSIS_CHARS} characters).`);
  }

  // Grammar runs on more text (LanguageTool is cheap); Gemini calls are capped via their own slicing
  const grammarText = text.slice(0, MAX_GRAMMAR_CHARS);

  const [grammarIssues, aiContent, suggestions, readabilityData, toneAnalysis] =
    await Promise.all([
      checkGrammar(grammarText),
      analyseAIContent(text),
      generateSuggestions(text),
      computeReadabilityScore(text),
      computeToneAnalysis(text),
    ]) as [GrammarIssue[], Awaited<ReturnType<typeof analyseAIContent>>, AISuggestion[], Awaited<ReturnType<typeof computeReadabilityScore>>, ToneAnalysis];

  const { score: readabilityScore, wordCount, sentenceCount, readingTimeMinutes, fleschGradeLevel, avgSentenceLength } = readabilityData;
  const plagiarismScore = computePlagiarismScore();
  const grammarScore = computeGrammarScore(wordCount, grammarIssues);

  return {
    aiLikelihoodScore: aiContent.score,
    aiReasoning: aiContent.reasoning,
    humanizationTips: aiContent.humanizationTips,
    grammarIssues,
    grammarScore,
    plagiarismScore,
    suggestions,
    readabilityScore,
    wordCount,
    sentenceCount,
    readingTimeMinutes,
    fleschGradeLevel,
    avgSentenceLength,
    toneAnalysis,
    analyzedAt: new Date(),
  };
}
