import { GoogleGenerativeAI } from '@google/generative-ai';
import { AISuggestion, AnalysisResult, GrammarIssue } from '../types';
import { checkGrammar } from './grammarCheck';

// ─── Gemini client (lazy init) ────────────────────────────────────────────────

let _gemini: GoogleGenerativeAI | null = null;

function getGemini(): GoogleGenerativeAI {
  if (!_gemini) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY is not configured');
    _gemini = new GoogleGenerativeAI(apiKey);
  }
  return _gemini;
}

// ─── AI Likelihood Scoring ────────────────────────────────────────────────────

async function scoreAILikelihood(text: string): Promise<number | null> {
  const sample = text.slice(0, 3000);

  const model = getGemini().getGenerativeModel({
    model: 'gemini-2.5-flash',
    generationConfig: {
      responseMimeType: 'application/json',
      temperature: 0.1,
    },
  });

  const prompt = `You are an expert in computational linguistics and AI detection.

Analyse the following text and estimate the probability (0–100) that it was generated by an AI language model.

Evaluation criteria:
- Sentence uniformity and rhythm
- Vocabulary diversity
- Presence of AI hedge phrases ("It is important to note…", "In conclusion…")
- Transitions and connective phrases
- Naturalness of idioms
- Specificity vs. generality

Return ONLY a JSON object (no markdown, no extra text):
{"aiLikelihoodScore": <number 0-100>, "reasoning": "<brief 1-sentence explanation>"}

Text:
"""
${sample}
"""`;

  try {
    const result = await model.generateContent(prompt);
    const raw = result.response.text().trim()
      .replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
    const parsed = JSON.parse(raw) as { aiLikelihoodScore?: number };
    return Math.min(100, Math.max(0, parsed.aiLikelihoodScore ?? 0));
  } catch (err) {
    console.error('AI likelihood scoring failed:', err);
    return null;
  }
}

// ─── Style Suggestions ────────────────────────────────────────────────────────

async function generateSuggestions(text: string): Promise<AISuggestion[]> {
  const sample = text.slice(0, 4000);

  const model = getGemini().getGenerativeModel({
    model: 'gemini-2.5-flash',
    generationConfig: {
      responseMimeType: 'application/json',
      temperature: 0.4,
    },
  });

  const prompt = `You are a professional editor and writing coach.

Review the following text and provide up to 5 improvement suggestions.
For each suggestion identify a specific passage and suggest how to improve it.

Return ONLY a valid JSON array (no markdown, no extra text):
[
  {
    "type": "rewrite|simplify|expand|tone",
    "original": "<exact excerpt from text, max 150 chars>",
    "suggested": "<improved version>",
    "reason": "<why this improvement helps>"
  }
]

Text:
"""
${sample}
"""`;

  try {
    const result = await model.generateContent(prompt);
    const raw = result.response.text().trim()
      .replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');

    const parsed = JSON.parse(raw) as AISuggestion[] | { suggestions?: AISuggestion[] };
    const suggestions = Array.isArray(parsed) ? parsed : (parsed.suggestions ?? []);
    return suggestions.slice(0, 5);
  } catch (err) {
    console.error('Suggestion generation failed:', err);
    return [];
  }
}

// ─── Readability Scoring ──────────────────────────────────────────────────────

function computeReadabilityScore(text: string): {
  score: number;
  wordCount: number;
  sentenceCount: number;
} {
  const words = text.trim().split(/\s+/).filter(Boolean);
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const wordCount = words.length;
  const sentenceCount = sentences.length;

  if (wordCount === 0 || sentenceCount === 0) {
    return { score: 0, wordCount, sentenceCount };
  }

  // Flesch Reading Ease approximation
  const avgSentenceLen = wordCount / sentenceCount;
  const avgSyllables =
    words.reduce((sum, w) => sum + estimateSyllables(w), 0) / wordCount;

  const score = Math.round(
    206.835 - 1.015 * avgSentenceLen - 84.6 * avgSyllables
  );

  return {
    score: Math.min(100, Math.max(0, score)),
    wordCount,
    sentenceCount,
  };
}

function estimateSyllables(word: string): number {
  word = word.toLowerCase().replace(/[^a-z]/g, '');
  if (word.length <= 3) return 1;
  const vowels = word.match(/[aeiouy]+/g);
  return vowels ? vowels.length : 1;
}

// ─── Plagiarism Placeholder ───────────────────────────────────────────────────
// Real implementation would call Copyscape, iThenticate, or similar API.

function computePlagiarismScore(): number {
  // Placeholder: returns 0 until a real plagiarism API is configured
  return 0;
}

// ─── Main Analysis Function ───────────────────────────────────────────────────

export async function analyseDocument(text: string): Promise<AnalysisResult> {
  if (!text || text.trim().length === 0) {
    throw new Error('Cannot analyse empty text');
  }

  // Run grammar check and AI scoring in parallel
  const [grammarIssues, aiLikelihoodScore, suggestions] = await Promise.all([
    checkGrammar(text),
    scoreAILikelihood(text),
    generateSuggestions(text),
  ]) as [GrammarIssue[], number | null, AISuggestion[]];

  const { score: readabilityScore, wordCount, sentenceCount } =
    computeReadabilityScore(text);

  const plagiarismScore = computePlagiarismScore();

  return {
    aiLikelihoodScore,
    grammarIssues,
    plagiarismScore,
    suggestions,
    readabilityScore,
    wordCount,
    sentenceCount,
    analyzedAt: new Date(),
  };
}
