import {
  Document as DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  PageBreak,
} from 'docx';
import { StructuredContent } from '../types';

export interface DocxExportOptions {
  title: string;
  author?: string;
}

export async function generateDocx(
  content: StructuredContent,
  options: DocxExportOptions
): Promise<Buffer> {
  const children: Paragraph[] = [];

  // ── Title ─────────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: options.title,
          bold: true,
          size: 56, // 28pt
          font: 'Calibri',
          color: '0F172A',
        }),
      ],
      spacing: { after: 200 },
    })
  );

  // Subtitle
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Ultimoversio — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
          size: 22,
          font: 'Calibri',
          color: '64748B',
          italics: true,
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Separator
  children.push(
    new Paragraph({
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' },
      },
      spacing: { after: 400 },
    })
  );

  // ── Sections ──────────────────────────────────────────────────────────────
  for (let i = 0; i < content.sections.length; i++) {
    const section = content.sections[i];

    // Page break before each section (except first)
    if (i > 0) {
      children.push(
        new Paragraph({
          children: [new PageBreak()],
        })
      );
    }

    // Section heading
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 120 },
      })
    );

    // Paragraphs
    for (const para of section.paragraphs) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: para,
              size: 24, // 12pt
              font: 'Calibri',
            }),
          ],
          spacing: { after: 200 },
          alignment: AlignmentType.LEFT,
        })
      );
    }
  }

  const doc = new DocxDocument({
    creator: options.author || 'Ultimoversio',
    title: options.title,
    description: 'Document exported from Ultimoversio',
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, right: 1080, bottom: 1440, left: 1080 },
          },
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}
