import PDFDocument from 'pdfkit';
import { StructuredContent } from '../types';

export interface PdfExportOptions {
  title: string;
  author?: string;
  includePageNumbers?: boolean;
}

export async function generatePdf(
  content: StructuredContent,
  options: PdfExportOptions
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 55, right: 55 },
        info: {
          Title: options.title,
          Author: options.author || 'Narrator Studio',
          Creator: 'Narrator Studio',
        },
        bufferPages: true,
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

      // ── Title page ────────────────────────────────────────────────────────
      doc.moveDown(6);

      // Accent bar
      doc.rect(55, doc.y - 5, 3, 40).fill('#4F46E5');

      doc.fontSize(28).font('Helvetica-Bold').fillColor('#0F172A')
        .text(options.title, 70, doc.y, { width: pageWidth - 20 });

      doc.moveDown(0.8);
      doc.fontSize(11).font('Helvetica').fillColor('#64748B')
        .text(`Generated by Narrator Studio`, 70);
      doc.fontSize(10)
        .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 70);

      // ── Content pages ──────────────────────────────────────────────────────
      for (const section of content.sections) {
        doc.addPage();

        // Section heading
        doc.fontSize(18).font('Helvetica-Bold').fillColor('#1E293B')
          .text(section.title, { width: pageWidth });

        // Separator line
        doc.moveDown(0.3);
        doc.moveTo(55, doc.y)
          .lineTo(55 + pageWidth, doc.y)
          .strokeColor('#E2E8F0')
          .lineWidth(1)
          .stroke();
        doc.moveDown(0.5);

        // Paragraphs
        doc.fontSize(11).font('Helvetica').fillColor('#334155');
        for (const paragraph of section.paragraphs) {
          if (doc.y > doc.page.height - 100) {
            doc.addPage();
          }
          doc.text(paragraph, { width: pageWidth, align: 'left', lineGap: 4 });
          doc.moveDown(0.6);
        }
      }

      // ── Page numbers ─────────────────────────────────────────────────────
      if (options.includePageNumbers !== false) {
        const pages = doc.bufferedPageRange();
        for (let i = pages.start; i < pages.start + pages.count; i++) {
          doc.switchToPage(i);
          doc.fontSize(9).font('Helvetica').fillColor('#94A3B8')
            .text(
              `${i + 1}`,
              0, doc.page.height - 40,
              { align: 'center', width: doc.page.width }
            );
        }
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
