import pptxgen from 'pptxgenjs';
import { StructuredContent, PPTExportOptions } from '../types';

interface ThemeConfig {
  background: string;
  textColor: string;
  accentColor: string;
  subTextColor: string;
  fontFamily: string;
}

const THEMES: Record<string, ThemeConfig> = {
  light: {
    background: 'FFFFFF',
    textColor: '1A1A2E',
    accentColor: '4F46E5',
    subTextColor: '6B7280',
    fontFamily: 'Calibri',
  },
  dark: {
    background: '1A1A2E',
    textColor: 'FFFFFF',
    accentColor: '818CF8',
    subTextColor: 'A0AEC0',
    fontFamily: 'Calibri',
  },
  professional: {
    background: 'F8FAFC',
    textColor: '0F172A',
    accentColor: '0369A1',
    subTextColor: '475569',
    fontFamily: 'Calibri',
  },
};

export async function generatePowerPoint(
  content: StructuredContent,
  options: PPTExportOptions
): Promise<Buffer> {
  const pptx = new pptxgen();
  const theme = THEMES[options.theme || 'professional'];

  pptx.defineLayout({ name: 'WIDESCREEN', width: 13.33, height: 7.5 });
  pptx.layout = 'WIDESCREEN';

  // ─── Title Slide ─────────────────────────────────────────────────────────
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: theme.background };

  // Accent bar
  titleSlide.addShape(pptxgen.ShapeType.rect, {
    x: 0,
    y: 3.2,
    w: 0.12,
    h: 1.1,
    fill: { color: theme.accentColor },
    line: { width: 0 },
  });

  titleSlide.addText(options.title, {
    x: 0.4,
    y: 2.8,
    w: 12,
    h: 1.2,
    fontSize: 36,
    bold: true,
    color: theme.textColor,
    fontFace: theme.fontFamily,
    align: 'left',
  });

  titleSlide.addText('Generated by Narrator Studio', {
    x: 0.4,
    y: 4.2,
    w: 12,
    h: 0.4,
    fontSize: 14,
    color: theme.subTextColor,
    fontFace: theme.fontFamily,
    align: 'left',
  });

  titleSlide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), {
    x: 0.4,
    y: 4.65,
    w: 6,
    h: 0.35,
    fontSize: 12,
    color: theme.subTextColor,
    fontFace: theme.fontFamily,
  });

  // ─── Content Slides ───────────────────────────────────────────────────────
  for (const section of content.sections) {
    if (!section.paragraphs || section.paragraphs.length === 0) continue;

    // Group paragraphs into slides (max 4 paragraphs per slide for readability)
    const PARA_PER_SLIDE = 4;
    const paraGroups: string[][] = [];

    for (let i = 0; i < section.paragraphs.length; i += PARA_PER_SLIDE) {
      paraGroups.push(section.paragraphs.slice(i, i + PARA_PER_SLIDE));
    }

    for (let groupIdx = 0; groupIdx < paraGroups.length; groupIdx++) {
      const slide = pptx.addSlide();
      slide.background = { color: theme.background };

      // Header bar
      slide.addShape(pptxgen.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.08,
        fill: { color: theme.accentColor },
        line: { width: 0 },
      });

      // Section title
      const titleText =
        paraGroups.length > 1
          ? `${section.title} (${groupIdx + 1}/${paraGroups.length})`
          : section.title;

      slide.addText(titleText, {
        x: 0.5,
        y: 0.2,
        w: 12.33,
        h: 0.6,
        fontSize: 22,
        bold: true,
        color: theme.accentColor,
        fontFace: theme.fontFamily,
      });

      // Separator line
      slide.addShape(pptxgen.ShapeType.rect, {
        x: 0.5,
        y: 0.85,
        w: 12.33,
        h: 0.02,
        fill: { color: theme.accentColor + '33' },
        line: { width: 0 },
      });

      // Paragraphs
      const bodyText = paraGroups[groupIdx]
        .map((p) => `• ${p}`)
        .join('\n\n');

      slide.addText(bodyText, {
        x: 0.5,
        y: 1.0,
        w: 12.33,
        h: 5.8,
        fontSize: 14,
        color: theme.textColor,
        fontFace: theme.fontFamily,
        align: 'left',
        valign: 'top',
        wrap: true,
        paraSpaceAfter: 8,
      });

      // Speaker notes
      if (options.includeNotes && section.narrationSegments?.length > 0) {
        const notes = section.narrationSegments.map((s) => s.text).join(' ');
        slide.addNotes(notes);
      }

      // Slide number
      slide.addText(`${groupIdx + 1}`, {
        x: 12.8,
        y: 7.1,
        w: 0.5,
        h: 0.3,
        fontSize: 9,
        color: theme.subTextColor,
        fontFace: theme.fontFamily,
        align: 'right',
      });
    }
  }

  // ─── Thank You Slide ──────────────────────────────────────────────────────
  const endSlide = pptx.addSlide();
  endSlide.background = { color: theme.accentColor };

  endSlide.addText('Thank You', {
    x: 0,
    y: 2.8,
    w: 13.33,
    h: 1.2,
    fontSize: 40,
    bold: true,
    color: 'FFFFFF',
    fontFace: theme.fontFamily,
    align: 'center',
  });

  endSlide.addText('Created with Narrator Studio', {
    x: 0,
    y: 4.2,
    w: 13.33,
    h: 0.5,
    fontSize: 14,
    color: 'FFFFFF',
    fontFace: theme.fontFamily,
    align: 'center',
  });

  // Write to buffer
  return pptx.write({ outputType: 'nodebuffer' }) as unknown as Promise<Buffer>;
}
