import pptxgen from 'pptxgenjs';
import { StructuredContent, PPTExportOptions } from '../types';

interface ThemeConfig {
  background: string;
  textColor: string;
  accentColor: string;
  subTextColor: string;
  fontFamily: string;
}

const THEMES: Record<string, ThemeConfig> = {
  light: {
    background: 'FFFFFF',
    textColor: '1A1A2E',
    accentColor: '4F46E5',
    subTextColor: '6B7280',
    fontFamily: 'Calibri',
  },
  dark: {
    background: '1A1A2E',
    textColor: 'FFFFFF',
    accentColor: '818CF8',
    subTextColor: 'A0AEC0',
    fontFamily: 'Calibri',
  },
  professional: {
    background: 'F8FAFC',
    textColor: '0F172A',
    accentColor: '0369A1',
    subTextColor: '475569',
    fontFamily: 'Calibri',
  },
};

export async function generatePowerPoint(
  content: StructuredContent,
  options: PPTExportOptions
): Promise<Buffer> {
  try {
    const pptx = new pptxgen();
    const theme = THEMES[options.theme || 'professional'];

    pptx.defineLayout({ name: 'WIDESCREEN', width: 13.33, height: 7.5 });
    pptx.layout = 'WIDESCREEN';

    // ─── Title Slide ─────────────────────────────────────────────────────────
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: theme.background };

    titleSlide.addText(options.title || 'Presentation', {
      x: 0.5,
      y: 3,
      w: 12.33,
      h: 1.5,
      fontSize: 44,
      bold: true,
      color: theme.textColor,
      fontFace: theme.fontFamily,
      align: 'center',
    });

    titleSlide.addText('Generated by Ultimoversio', {
      x: 0.5,
      y: 4.8,
      w: 12.33,
      h: 0.5,
      fontSize: 16,
      color: theme.subTextColor,
      fontFace: theme.fontFamily,
      align: 'center',
    });

    // ─── Content Slides ───────────────────────────────────────────────────────
    const sections = content?.sections || [];
    
    if (sections.length === 0) {
      // No sections - create a single slide with message
      const slide = pptx.addSlide();
      slide.background = { color: theme.background };
      slide.addText('No content available', {
        x: 0.5,
        y: 3,
        w: 12.33,
        h: 1,
        fontSize: 24,
        color: theme.subTextColor,
        fontFace: theme.fontFamily,
        align: 'center',
      });
      slide.addText('Please structure your document first', {
        x: 0.5,
        y: 4,
        w: 12.33,
        h: 0.5,
        fontSize: 14,
        color: theme.subTextColor,
        fontFace: theme.fontFamily,
        align: 'center',
      });
    } else {
      for (const section of sections) {
        if (!section.paragraphs || section.paragraphs.length === 0) continue;

        // Group paragraphs into slides (max 4 paragraphs per slide for readability)
        const PARA_PER_SLIDE = 4;
        const paraGroups: string[][] = [];

        for (let i = 0; i < section.paragraphs.length; i += PARA_PER_SLIDE) {
          paraGroups.push(section.paragraphs.slice(i, i + PARA_PER_SLIDE));
        }

        for (let groupIdx = 0; groupIdx < paraGroups.length; groupIdx++) {
          const slide = pptx.addSlide();
          slide.background = { color: theme.background };

          // Section title
          const titleText =
            paraGroups.length > 1
              ? `${section.title} (${groupIdx + 1}/${paraGroups.length})`
              : section.title;

          slide.addText(titleText, {
            x: 0.5,
            y: 0.5,
            w: 12.33,
            h: 0.8,
            fontSize: 28,
            bold: true,
            color: theme.accentColor,
            fontFace: theme.fontFamily,
          });

          // Paragraphs
          const bodyText = paraGroups[groupIdx]
            .map((p) => `• ${p}`)
            .join('\n\n');

          slide.addText(bodyText, {
            x: 0.5,
            y: 1.5,
            w: 12.33,
            h: 5.5,
            fontSize: 16,
            color: theme.textColor,
            fontFace: theme.fontFamily,
            align: 'left',
            valign: 'top',
          });

          // Speaker notes
          if (options.includeNotes && section.narrationSegments?.length > 0) {
            const notes = section.narrationSegments.map((s) => s.text).join(' ');
            slide.addNotes(notes);
          }
        }
      }
    }

    // ─── Thank You Slide ──────────────────────────────────────────────────────
    const endSlide = pptx.addSlide();
    endSlide.background = { color: theme.accentColor };

    endSlide.addText('Thank You', {
      x: 0,
      y: 3,
      w: 13.33,
      h: 1.5,
      fontSize: 48,
      bold: true,
      color: 'FFFFFF',
      fontFace: theme.fontFamily,
      align: 'center',
    });

    // Write to buffer
    console.log('[PPTX] Writing to buffer...');
    const buffer = await (pptx.write({ outputType: 'nodebuffer' }) as Promise<Buffer>);
    console.log('[PPTX] Buffer created, size:', buffer.length);
    return buffer;
  } catch (err) {
    console.error('[PPTX] Generation failed:', err);
    throw new Error('Failed to generate PowerPoint: ' + (err instanceof Error ? err.message : 'Unknown error'));
  }
}
